defaults:
  - _self_
intrinsic:
  type: rnd
  encoding_size: 32
  lr: 0.0003
  int_coef: 1
  ext_coef: 2
  reward_normalisation: true
  normalised_obs_clip: 5
env:
  name: MountainCar-v0
  max_episode_steps: 100
cats:
  fixed_reset: true
  death_not_end: false
  reset_action:
    enable: false
    penalty: 0.0
  env_action_noise: 0.0
  teleport:
    enable: false
    type: e_greedy
    kwargs:
      e: 0.1
    memory:
      type: fifo
      capacity: 1024
train:
  total_frames: 4096
  initial_collection_size: 0
algorithm:
  gamma: 0.99
  lmbda: 0.9
  n_update_epochs: 4
  minibatch_size: 32
  collection_batch: 100
policy:
  p: 0
log:
  name: false
  checkpoint:
    enable: false
  evaluation:
    video:
      enable: false
      path:
  frames_per_epoch: 100
  path: log
seed: 0
